name = "url-shortener"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true
compatibility_date = "2022-01-19"

kv_namespaces = [ 
    { binding = "URLS" }
]

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
